### ISSUE TITLE
Not seeing new APM service in Elastic when using the extension

### ISSUE THREAD

**Issue by rpivovar-godaddy** [elastic/apm-aws-lambda#103]
I'm attempting to use the apm-aws-lambda manual installation alongside the elastic-apm-node package.

### Expectation

After instrumenting both apm-aws-lambda and elastic-apm-node for a lambda handler, I'm invoking this handler in hopes that I see a new service inside the APM > Services section of our Elastic dashboard.

### Reality

I'm not seeing a new service inside the APM > Services section or our Elastic dashboard. However, I do see the extension's logs in the handler's log group.

### Details

To set this up, I followed the [Manual Installation](https://github.com/elastic/apm-aws-lambda/blob/main/docs/aws-lambda-extension.asciidoc#manual-installation) section of the AWS Lambda Extension docs.

I downloaded the **x86_64** version of the extension zip and uploaded to AWS. I set compatible runtimes for this layer to **nodejs12.x**. I configured the handler to use this layer, and it appears to be doing so based on the Cloudwatch logging.

Based on the [Configure your Environment Variables](https://github.com/elastic/apm-aws-lambda/blob/main/docs/aws-lambda-extension.asciidoc#configure-your-environment-variables) section of the docs, I set these environment variables for the handler:

- `ELASTIC_APM_CENTRAL_CONFIG`: `false`
- `ELASTIC_APM_CLOUD_PROVIDER`: `none`
- `ELASTIC_APM_LAMBDA_APM_SERVER`: `https://xxxxxxxx.elastic-cloud.com:9243`
- `ELASTIC_APM_API_KEY`: `xxxxxxxxxxxxxx`
- `ELASTIC_APM_SERVER_URL`: `http://localhost:8200`

We are also using the value for the `ELASTIC_APM_LAMBDA_APM_SERVER` variable in a different service (Fargate), and that is working as expected since we are seeing that service name populate in the APM > Services section of our Elastic dashboard.

For the `ELASTIC_APM_API_KEY` value, we created a brand new API key in Elastic and set the variable to the **base64** version of this value. We did not update any permissions on the API key and created it with all default settings.

Inside the handler, we have set up elastic-apm-node like so:

```js
const apm = require('elastic-apm-node').start({
  apiKey: process.env.ELASTIC_APM_API_KEY,
  serverUrl: process.env.ELASTIC_APM_LAMBDA_APM_SERVER
});

exports.handler = apm.lambda(async function (event) {
    ...
});
```

The logs for a single handler invocation are fairly short and seem to provide some details that indicate the extension is working. Here are the complete logs with some private details omitted:

```
--
START RequestId: xxxxxxxxxxxxxxxxx Version: $LATEST
2022/01/19 14:01:30 xxxxxxxxxxxxxxxxx
2022/01/19 14:01:30 Register response: {
"functionName": "xxxxxxxxxxxxxxxxx",
"functionVersion": "$LATEST",
"handler": "index.xxxxxxxxxxxxxxxxx.handler"
}
2022/01/19 14:01:30 Could not read ELASTIC_APM_DATA_RECEIVER_TIMEOUT_SECONDS, defaulting to 15: strconv.Atoi: parsing "": invalid syntax
2022/01/19 14:01:30 Extension listening for apm data on :8200
LOGS	Name: apm-lambda-extension	State: Subscribed	Types: [platform]
2022/01/19 14:01:30 Waiting for next event...
2022/01/19 14:01:30 Server listening for logs data from AWS Logs API on sandbox:1234
EXTENSION	Name: apm-lambda-extension	State: Ready	Events: [INVOKE,SHUTDOWN]
2022/01/19 14:01:31 Received event: {
"eventType": "INVOKE",
"deadlineMs": 1642600921931,
"requestId": "xxxxxxxxxxxxxxxxx",
"invokedFunctionArn": "arn:aws:lambda:xxxxxxxxxxxxxxxxx",
"tracing": {
"type": "X-Amzn-Trace-Id",
"value": "Root=1-61e819b7-5d9e8dd4158fe1886c76e76f;Parent=58b2c1345e804c91;Sampled=1"
}
}
2022/01/19 14:01:31 Checking for agent data
2022/01/19 14:01:31 No agent data on buffer
2022/01/19 14:01:31 Received log event platform.logsSubscription
2022/01/19 14:01:31 Received log event platform.start
2022/01/19 14:01:31 Received log event platform.extension
2022-01-19T14:01:32.029Z	xxxxxxxxxxxxxxxxx	INFO xxxxxxxxxxxxxxxxx
2022/01/19 14:01:33 Adding agent data to buffer to be sent to apm server
END RequestId: xxxxxxxxxxxxxxxxx
REPORT RequestId: xxxxxxxxxxxxxxxxx	Duration: 1918.42 ms	Billed Duration: 1919 ms	Memory Size: 128 MB	Max Memory Used: 122 MB	Init Duration: 1591.33 ms	XRAY TraceId: xxxxxxxxxxxxxxxxx	SegmentId: 58b2c1345e804c91	Sampled: true
```

<hr />

Based on the above, does it look like we are misconfiguring something here?

Thanks for the help!

**Comment by astorm** [comment]
Thanks for giving the Lambda extension a try @rpivovar-godaddy _and_ for the detailed information about your configuration.  Let's see what we can do to get you up and running.  

Looking over your configuration the first thing that pops out is this

```
const apm = require('elastic-apm-node').start({
  apiKey: process.env.ELASTIC_APM_API_KEY,
  serverUrl: process.env.ELASTIC_APM_LAMBDA_APM_SERVER
});
```

I would expect to see something more like 

```
const apm = require('elastic-apm-node').start({});
```

That is, you shouldn't need to configure these variables when using the Node.js agent in Amazon Lambda.  

With the Lambda extension it's intended that you configure your agent values via the _Environment Variables_ tab in Lambda.  While you _can_ set additional values via the agent's `start` method, it's a little too easy to accidentally overwrite a value. With the configuration you included, the agent was trying to send data _directly_ to your APM Server endpoint instead of the extension.

**More Details**: Sending data directly to APM Server doesn't always work with Lambda -- if the HTTP request to send the data takes longer than the Lambda's freeze or shutdown phases, the data won't be sent.  It's not obvious, but this is why APM vendors need to use an extension based solution in the first place.    

The agent actually needs to send data to `http://localhost:8200` URL (which is the extension) and then the extension forwards it on to the `https://xxxxxxxx.elastic-cloud.com:9243` URL.  Without getting _too_ deep into the Amazon internals, Lambda Extensions have special permission to run in the background so they avoid the problems that come with posting data directly to a server. 

Your _Environment Variables_ tab looks correct. So, to start, I'd say let's get those fields out of the `start` method and give it another try.  I _believe_ that will clear up your problem.  If it doesn't let us know what you're seeing in the logs and we'll get you up and running ASAP.

**Comment by rpivovar-godaddy** [comment]
Thanks @astorm for the explanation and the help -- that makes sense. I think I'm a little further now, but still not seeing the new service show up in the APM dashboard.

Based on logs, it looks like the payloads are going to the right place now, but it looks like I'm failing authentication.

Below are the logs for several invocations within a 5-minute period.

```
START RequestId: xxxxxxxxxxxxx Version: $LATEST
--
2022/01/19 16:44:09 Received log event platform.runtimeDone
2022/01/19 16:44:09 Received runtimeDone event for this function invocation
2022/01/19 16:44:09 Received runtimeDone signal
2022/01/19 16:44:09 Checking for agent data
2022/01/19 16:44:09 No agent data on buffer
2022/01/19 16:44:09 Waiting for next event...
2022/01/19 16:48:24 Error sending to APM server, skipping: failed to post to APM server: Post "https://xxxxxxxxxxxxx.elastic-cloud.com:9243/intake/v2/events": net/http: TLS handshake timeout
2022/01/19 16:48:24 funcDone signal received, not processing any more agent data
2022-01-19T16:48:24.818Z	0f6182f3-7eb5-4a0d-8012-cb58e5ca9f6c	INFO	xxxxxxxxxxxxx
2022/01/19 16:48:24 Received event: {
"eventType": "INVOKE",
"deadlineMs": 1642610934811,
"requestId": "xxxxxxxxxxxxx",
"invokedFunctionArn": "arn:aws:lambda:xxxxxxxxxxxxx",
"tracing": {
"type": "X-Amzn-Trace-Id",
"value": "Root=1-61e840d8-33d3a4d348a2ed7a1c879d29;Parent=7bba51a71b0dff24;Sampled=1"
}
}
2022/01/19 16:48:24 Checking for agent data
2022/01/19 16:48:24 No agent data on buffer
2022/01/19 16:48:24 Received log event platform.end
2022/01/19 16:48:25 Received log event platform.report
2022/01/19 16:48:25 Received log event platform.start
2022/01/19 16:48:25 Adding agent data to buffer to be sent to apm server
2022/01/19 16:48:26 Received log event platform.runtimeDone
2022/01/19 16:48:26 Received runtimeDone event for this function invocation
2022/01/19 16:48:26 Received runtimeDone signal
2022/01/19 16:48:26 Checking for agent data
2022/01/19 16:48:26 No agent data on buffer
2022/01/19 16:48:26 Waiting for next event...
END RequestId: xxxxxxxxxxxxx
REPORT RequestId: xxxxxxxxxxxxx	Duration: 1226.03 ms	Billed Duration: 1227 ms	Memory Size: 128 MB	Max Memory Used: 121 MB	XRAY TraceId: 1-61e840d8-33d3a4d348a2ed7a1c879d29	SegmentId: 7bba51a71b0dff24	Sampled: true
START RequestId: xxxxxxxxxxxxx Version: $LATEST
2022/01/19 16:48:29 Received event: {
"eventType": "INVOKE",
"deadlineMs": 1642610939458,
"requestId": "xxxxxxxxxxxxx",
"invokedFunctionArn": "arn:aws:lambda:xxxxxxxxxxxxx",
"tracing": {
"type": "X-Amzn-Trace-Id",
"value": "Root=1-61e840dd-44a171e14f071e9b46a23664;Parent=0e351b8a33c58434;Sampled=1"
}
}
2022/01/19 16:48:29 Checking for agent data
2022/01/19 16:48:29 No agent data on buffer
2022/01/19 16:48:29 Received log event platform.end
2022/01/19 16:48:29 Received log event platform.report
2022/01/19 16:48:29 Received log event platform.start
2022-01-19T16:48:30.037Z	xxxxxxxxxxxxx	INFO	xxxxxxxxxxxxx
2022/01/19 16:48:30 Adding agent data to buffer to be sent to apm server
2022/01/19 16:48:30 Received log event platform.runtimeDone
2022/01/19 16:48:30 Received runtimeDone event for this function invocation
2022/01/19 16:48:30 Received runtimeDone signal
2022/01/19 16:48:30 Checking for agent data
2022/01/19 16:48:30 No agent data on buffer
2022/01/19 16:48:30 Waiting for next event...
END RequestId: xxxxxxxxxxxxx
REPORT RequestId: xxxxxxxxxxxxx	Duration: 1379.28 ms	Billed Duration: 1380 ms	Memory Size: 128 MB	Max Memory Used: 123 MB	XRAY TraceId: 1-61e840dd-44a171e14f071e9b46a23664	SegmentId: 0e351b8a33c58434	Sampled: true
START RequestId: xxxxxxxxxxxxx Version: $LATEST
2022/01/19 16:48:32 Received event: {
"eventType": "INVOKE",
"deadlineMs": 1642610942096,
"requestId": "xxxxxxxxxxxxx",
"invokedFunctionArn": "arn:aws:lambda:xxxxxxxxxxxxx",
"tracing": {
"type": "X-Amzn-Trace-Id",
"value": "Root=1-61e840e0-2b90f02b2444501a4c47c867;Parent=225fb9bb1ff7efa7;Sampled=1"
}
}
2022/01/19 16:48:32 Checking for agent data
2022/01/19 16:48:32 No agent data on buffer
2022/01/19 16:48:32 Received log event platform.end
2022/01/19 16:48:32 Received log event platform.report
2022-01-19T16:48:32.097Z	3d07a330-8dd1-4ae8-8399-2a493ca40e84	INFO	xxxxxxxxxxxxx
2022/01/19 16:48:32 APM server response body: {     "error": "authentication failed" }
 
2022/01/19 16:48:32 APM server response status code: 401
2022/01/19 16:48:32 funcDone signal received, not processing any more agent data
2022/01/19 16:48:32 APM server response body: {     "error": "authentication failed" }
 
2022/01/19 16:48:32 APM server response status code: 401
2022/01/19 16:48:32 funcDone signal received, not processing any more agent data
2022/01/19 16:48:32 Received log event platform.start
2022/01/19 16:48:32 Adding agent data to buffer to be sent to apm server
2022/01/19 16:48:32 APM server response body: {     "error": "authentication failed" }
 
2022/01/19 16:48:32 APM server response status code: 401
2022/01/19 16:48:32 Received log event platform.runtimeDone
2022/01/19 16:48:32 Received runtimeDone event for this function invocation
2022/01/19 16:48:32 Received runtimeDone signal
2022/01/19 16:48:32 Checking for agent data
2022/01/19 16:48:32 No agent data on buffer
2022/01/19 16:48:32 Waiting for next event...
2022/01/19 16:48:32 funcDone signal received, not processing any more agent data
END RequestId: xxxxxxxxxxxxx
REPORT RequestId: xxxxxxxxxxxxx	Duration: 287.92 ms	Billed Duration: 288 ms	Memory Size: 128 MB	Max Memory Used: 123 MB	XRAY TraceId: 1-61e840e0-2b90f02b2444501a4c47c867	SegmentId: 225fb9bb1ff7efa7	Sampled: true
```

We are using version 7.15.2 of Elastic -- it looks like the API key should work for this version.

I also followed along with this thread ["401 Unathorized when trying to call the Kibana API"](https://discuss.elastic.co/t/401-unathorized-when-trying-to-call-the-kibana-api/263225) which looked like a similar issue.

I tried making this curl request from the thread:

```
curl -v --location --request GET 'https://xxxxxxxxxxxxx.elastic-cloud.com:9243/_security/_authenticate' \
--header 'Authorization: ApiKey xxxxxxxxxxxxx'
```

And got this response:

```
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 54.189.80.227...
* TCP_NODELAY set
* Connected to xxxxxxxxxxxxx.elastic-cloud.com (xxxxxxxxxxxxx) port 9243 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.xxxxxxxxxxxxx.elastic-cloud.com
*  start date: Jan 11 00:02:20 2022 GMT
*  expire date: Apr 11 00:02:19 2022 GMT
*  subjectAltName: host "xxxxxxxxxxxxx.elastic-cloud.com" matched cert's "*.xxxxxxxxxxxxx.elastic-cloud.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fedda009200)
> GET /_security/_authenticate HTTP/2
> Host: xxxxxxxxxxxxx.elastic-cloud.com:9243
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: ApiKey xxxxxxxxxxxxx
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404
< content-type: application/json
< date: Wed, 19 Jan 2022 16:38:12 GMT
< x-cloud-request-id: 1eEQ61amSCapsK0nb2UJqA
< x-content-type-options: nosniff
< x-found-handling-cluster: 1a098c00d32543fd95fe7ad5ec57cfce
< x-found-handling-instance: instance-0000000002
< content-length: 36
<
{
  "error": "404 page not found"
}
* Connection #0 to host xxxxxxxxxxxxx.elastic-cloud.com left intact
* Closing connection 0
```

Not 100% sure the meaning of this response. I'll also add that this API key was made from my user account, and I do not have superuser permissions in Elastic (I can't view Users/Roles/Role Mappings in the dashboard).

It looks like there is an authentication issue with my API key.

**Comment by astorm** [comment]
> It looks like there is an authentication issue with my API key.

@rpivovar-godaddy  Agreed -- just for completeness the following logs indicate an authentication error.

```
2022/01/19 16:48:32 APM server response status code: 401
2022/01/19 16:48:32 funcDone signal received, not processing any more agent data
2022/01/19 16:48:32 APM server response body: {     "error": "authentication failed" }
```

That's an HTTP status code of 401, which indicates the request is _Unauthorized_.

So I think I see the next problem with your Lambda configuration, and then a second problem with the ElasticSearch API URL you're using.  I'm going to cover each separately. 

**Re: next steps Lambda configuration**

Looking over the latest information you sent over and re-reading your previous post, I think I see another issue/point-of-confusion.

The `ELASTIC_APM_LAMBDA_APM_SERVER` value should point at your _APM Server_ endpoint and NOT your ElasticSearch API endpoint.  These are two different URLs

The port you have in your value (`9243`) makes me believe this is your Elastic API endpoint and NOT your APM Server endpoint.   You can get your APM Server endpoint by navigating to 

    Cloud -> Deployments -> [Specific Deployment]
    
and then looking at the applications section

<img width="462" alt="Screen Shot 2022-01-19 at 10 14 48 AM" src="https://user-images.githubusercontent.com/184372/150195473-1c709ec3-9fb7-4d5e-be84-9977cee73373.png">

    
If you click on the _Copy Endpoint_ link next to APM you'll copy the APM Server endpoint to your clipboard, and can paste it in to the `ELASTIC_APM_LAMBDA_APM_SERVER` value in your environment configuration. 

Does that make sense/get you pointed in the right direction?

**Re: your API Key**

I saw you tried to test your API key by making an API request to an ElasticSearch API endpoint via curl

```
curl -v --location --request GET 'https://xxxxxxxxxxxxx.elastic-cloud.com:9243/_security/_authenticate' \
--header 'Authorization: ApiKey xxxxxxxxxxxxx'
```

and got back 

```
{
  "error": "404 page not found"
}
```

This also confuses me.  I would expect you to receive either a response that listed your credentials -- something like this

```
% curl --location --request GET 'https://xxx.us-east-1.aws.found.io:9243/_security/_authenticate' \                                                                                     
--header 'Authorization: ApiKey yyy'

{
  "username": "someusername",
  "roles": [],
  "full_name": "Bob Jenkins",
  "email": "bob@example.com",
  "metadata": {},
  "enabled": true,
  "authentication_realm": {
    "name": "_es_api_key",
    "type": "_es_api_key"
  },
  "lookup_realm": {
    "name": "_es_api_key",
    "type": "_es_api_key"
  },
  "authentication_type": "api_key"
}

```

or to get back an unauthorized response. 

```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "missing authentication credentials for REST request [/_security/_authenticate]",
        "header": {
          "WWW-Authenticate": [
            "Basic realm=\"security\" charset=\"UTF-8\"",
            "Bearer realm=\"security\"",
            "ApiKey"
          ]
        }
      }
    ],
    "type": "security_exception",
    "reason": "missing authentication credentials for REST request [/_security/_authenticate]",
    "header": {
      "WWW-Authenticate": [
        "Basic realm=\"security\" charset=\"UTF-8\"",
        "Bearer realm=\"security\"",
        "ApiKey"
      ]
    }
  },
  "status": 401
}

``` 

The fact that your response is a _404 page not found_ makes me wonder if `https://xxxxxxxxxxxxx.elastic-cloud.com:9243` is the correct URL, and if it is the correct URL it would make me wonder if the computer your made the request from has access to that URL (routing, firewalls, etc.)  This specific issue with `xxxxxxxxxxxxx.elastic-cloud.com:9243` might be better handled by our [traditional support channels](https://www.elastic.co/guide/en/cloud/current/ec-get-help.html) -- I'm not sure how you'all have your cluster(s) setup/configured and even if I did I don't have access to those particular levers :) 

That said, let me know if the APM Server info about clears up your problem or not.

**Comment by rpivovar-godaddy** [comment]
Hi @astorm -- following up here. apm-aws-lambda does work with elastic-apm-node after making the above fixes. I do see our app showing up in APM. I'm still having an issue with secrets, which I will share on #105. Feel free to close this issue. Thanks again for the help.
