### ISSUE TITLE
Support for Metrics

### ISSUE THREAD

**Issue by astorm** [elastic/apm-aws-lambda#108]
We should decide on a strategy for reporting metrics (such as memory usage, total available memory, billing duration/init duration, etc.).  This may mean making the agent's metrics work inside a lambda function, it may mean using [the Lambda Logs API](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-logs-api.html) to look for and report metrics, it may means leveraging [metric beat](https://www.elastic.co/beats/metricbeat) or [function beat](https://www.elastic.co/beats/functionbeat), or may mean some other thing.

- [ ] Decide on Metrics Strategy 
- [ ] Decide which Metrics to Collect
- [ ] Expose Lambda specific metrics via UI

**Comment by AlexanderWert** [comment]
Community & customer feedback:
- a solution that does not involve interaction with CloudWatch is preferred for costs and rate limiting reasons 
- metrics indicating efficiency would be very valuable (throttles, CPU time/usage, Memory consumption)

Proposal: let's start as simple as collecting the metrics provided by the Lambda platform logs:
- Duration
- Billed Duration
- Memory Size
- Memory Used
- Init Duration

**Comment by jlvoiseux** [comment]
Was closed by mistake upon merging #202 - We still need to update the APM model to properly include faas information alongside the metrics (ie. replace `labels.faas_xxxx` by `faas.xxxx`).

**Comment by axw** [comment]
With https://github.com/elastic/apm-server/pull/8400 merged, I think we can close this. Server support will be in 8.4.
