### ISSUE TITLE
Published ARN Names should Include Release Version and "Elastic"

### ISSUE THREAD

**Issue by astorm** [elastic/apm-aws-lambda#110]
Currently, our build scripts create an extension ARN with a name like

    arn:aws:lambda:us-west-2:123456789123:layer:apm-lambda-extension:80

Amazon automatically embeds the _layer_ version into this ARN (above this is `80`)

We'd like to include the version of the Lambda extension in this layer as well. That is, if we were publishing version `0.0.3` of the extension, we would want to end up with layer name that looked like 

    arn:aws:lambda:us-west-2:123456789123:layer:elastic-apm-lambda-extension-ver-0-0-3:80

The intent of this change would be to tie the name of the ARN with the version of the extension, allowing us to quickly identify which version of the extension's being used without keeping an "ARN version to Extension version" map. It would also bring us in line with what ADOT does with its OpenTelemetry layers ([example](https://aws-otel.github.io/docs/getting-started/lambda/lambda-js))

If this isn't possible we'd like to include the extension version in the table we're publishing of the ARNs so that a specific ARN can be mapped back to a specific extension version.

- [ ] Are we including the extension version in the ARN name, or are we publishing the layer version alongside the ARN in the ASCII doc table
- [ ] Do what we're doing 🤠

**Comment by trentm** [comment]
@astorm 

1. Can we please add "elastic" to the layer name?  Perhaps something like `arn:aws:lambda:<region>:123456789123:layer:elastic-apm-extension-ver-0-0-3:<ver>`.    The "lambda" part of the name could be elided if we want to be shorter, given that "lambda" is required earlier in the full ARN.
2. Do we have separate builds for the separate architectures? If so, do we need the arch in the name as well?

(Happy to make this a separate ticket(s) if you prefer.)

**Comment by astorm** [comment]
@trentm no objections to including elastic in the name and it seems to make sense to do it in this issue -- it should just be a string change (I'll leave @v1v to let us know if I'm missing something obvious)

Also, we do need to publish different ARN for x86 and arm and might already be accounted for in the same -- see the open PR for ARN naming.  https://github.com/elastic/apm-aws-lambda/pull/101
