### ISSUE TITLE
ELASTIC_APM_SERVICE_NAME not setting the service name in Elastic Cloud

### ISSUE THREAD

**Issue by lageorgem** [elastic/apm-aws-lambda#123]
I have added the Lambda layer successfully, and I see data coming into the Elastic Cloud solution, however, when I try to set the env var `ELASTIC_APM_SERVICE_NAME: "my-service-name"`, the service is reported to elastic using the `AWS_LAMBDA_FUNCTION_NAME` env var still.

My serverless config provides the following env vars:

```    ELASTIC_HOST: ${env:ELASTIC_HOST}
    ELASTIC_USER: ${env:ELASTIC_USER}
    ELASTIC_PASSWORD: ${env:ELASTIC_PASSWORD}
    ELASTIC_APM_CENTRAL_CONFIG: false
    ELASTIC_APM_CLOUD_PROVIDER: "none"
    ELASTIC_APM_LAMBDA_APM_SERVER: "https://blabla.apm.us-east-1.aws.cloud.es.io:443"
    ELASTIC_APM_SECRET_TOKEN: "secret"
    ELASTIC_APM_SERVER_URL: "http://localhost:8200"
    ELASTIC_APM_SERVICE_NAME: "my-service"
```

And the layer is added via ARN, with no installation procedure

**Comment by AlexanderWert** [comment]
Closing as it is included in https://github.com/elastic/apm-agent-nodejs/issues/2531
