### ISSUE TITLE
published extension layers should set "Compatible architectures"

### ISSUE THREAD

**Issue by trentm** [elastic/apm-aws-lambda#141]
Currently our publishing of extension layers do not specify the compatible architecture. That looks like this in the AWS console:

<img width="745" alt="Screen Shot 2022-03-04 at 4 06 44 PM" src="https://user-images.githubusercontent.com/46866/156858366-4d9d6f6b-d2f9-48a8-b3a8-4b15ac042052.png">

The result is that one can accidentally select an incompatible ARN from the releases table and the suggested "Verify" in the AWS Console won't help.  This causes a *somewhat* obvious error when attempting to run or test the function directly, you get this response:

```
{
  "errorMessage": "RequestId: 2770acd9-e8b3-4043-b246-d68fbeb94f02 Error: fork/exec /opt/extensions/apm-lambda-extension: exec format error",
  "errorType": "Extension.LaunchError"
}
```

and a similar error message in the logs.

However, if the function is being invoked by some trigger, e.g. API Gateway, it is less obvious what is wrong:

```
% curl -i https://REDACTED.execute-api.us-west-2.amazonaws.com/defaulttrentstage/trentm-play-fn1
HTTP/2 500
date: Sat, 05 Mar 2022 00:11:57 GMT
content-type: application/json
content-length: 35
apigw-requestid: Oe-gHhxsvHcESMg=

{"message":"Internal Server Error"}
```

Adding this *should* just mean adding `--compatible-architectures "$(ARCHITECTURE)"` to the `aws lambda publish-layer-version` call here: https://github.com/elastic/apm-aws-lambda/blob/eb3f0417ad9a37cff9abbafd429003fc2d082dbe/apm-lambda-extension/Makefile#L59-L67

**Comment by trentm** [comment]
This requires at least v2.2.43 of the aws-cli: https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst#L670
> * api-change:``lambda``: Adds support for Lambda functions powered by AWS Graviton2 processors. Customers can now select the CPU architecture for their functions.

**Comment by v1v** [comment]
I forgot that we removed this in https://github.com/elastic/apm-aws-lambda/pull/112 as some regions are not compatible with some architectures :/ 

see https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp/detail/v0.0.4/1/pipeline/
