### ISSUE TITLE
Running extension without Secret token and API Key

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-aws-lambda#180]
Currently the extension won't start if neither an `ELASTIC_APM_SECRET_TOKEN ` nor an 'ELASTIC_APM_API_KEY' is provided:

```
2022-04-06T16:49:39.728-04:00 {"@timestamp":"2022-04-06T20:49:39.727Z",
"ecs.version":"1.6.0","event.dataset":"apm-lambda-extension","log.level":"fatal",
"message":"please set ELASTIC_APM_SECRET_TOKEN or ELASTIC_APM_API_KEY, exiting"}
```

Can we loosen this requirement for users who operate their own APM Server and don't need / want to use a secured connection between extension and the APM server?

**Comment by simitt** [comment]
Please log a warning if no auth is provided.
