### ISSUE TITLE
Support TLS configuration options

### ISSUE THREAD

**Issue by simitt** [elastic/apm-aws-lambda#186]
At a minimum we should support 
* enable/disable server cert validation
* configure a CA certificate for allowing custom certificates

@felixbarny  what are the minimum TLS related settings that you would expect from the lambda extension for feature parity with elastic apm agents?

**Comment by akhileshpok** [comment]
@simitt - Do we have an idea about how much effort is required to implement this enhancement? Thanks

**Comment by axw** [comment]
Closed by https://github.com/elastic/apm-aws-lambda/pull/357
