### ISSUE TITLE
Find alternative way to provide Logs API Listener network info to main_test.go

### ISSUE THREAD

**Issue by jlvoiseux** [elastic/apm-aws-lambda#193]
As [mentioned](https://github.com/elastic/apm-aws-lambda/pull/191#discussion_r866454169_) in #191:

> We shouldn't be setting globals, and definitely shouldn't have test code mixed into the production code.

**Comment by kruskall** [comment]
This was solved by https://github.com/elastic/apm-aws-lambda/pull/248.

Now there is no global state and the address can be passed with functional options. I will close this!
