### ISSUE TITLE
Create support enablement material

### ISSUE THREAD

**Issue by simitt** [elastic/apm-aws-lambda#200]
Additional to existing public documentation, create a training video and internal documentation for onboarding the support team.

**Comment by jlvoiseux** [comment]
A set of videos as well as the associated slides are available [here](https://drive.google.com/drive/folders/1DzbTBqaamBh9H6iPOhHQ0bGt6XNvr8EI?usp=sharing). Let me know what you think.

**Comment by simitt** [comment]
The material is great! This can be closed now.

**Comment by insukcho** [comment]
@jlvoiseux Thank you for the great materials. 

Do we have any additional troubleshooting guidelines for AWS lambda extension? For example, what kind of information should I collect if I have issues monitoring AWS Lambda Functions?

I would like to check the list below at least:
- is my AWS Lamda function (which is holding apm agent)  communicating with the AWS Lambda Execution layer without issues?
- is the AWS Lambda Execution layer without issues communicating with the APM Server/Integrations properly?
- How to check any performance issues on Lambda side?
- How to isolate the issue between the Lambda service or Lambda extension?

CC: @simitt

**Comment by simitt** [comment]
Good questions @insukcho - any issues between the lambda extension and the APM Server should be surfaced via the logs in the components. If you run into any issues I'd therefore recommend collecting the logs. 
Performance issues might be specific and a lot of testing was done in the past; let's discuss this if we see concrete issues. 

At the momment I'd refrain from adding a troubleshooting section to the public docs as we haven't seen a lot of issues yet.

**Comment by insukcho** [comment]
Thanks for the clarification.

Which logs should I collect from where? Is it the same logs from Lambda
function layer?
