### ISSUE TITLE
Add Smoke Testing to the CI pipeline

### ISSUE THREAD

**Issue by jlvoiseux** [elastic/apm-aws-lambda#217]
Following the deployment of a broken release ([v1.0.1](https://github.com/elastic/apm-aws-lambda/releases/tag/v1.0.1)), it has been suggested to introduce smoke testing to the repository. These smoke tests would take inspiration from [elastic-lambda-extension-testing](https://github.com/elastic/apm-lambda-extension-testing) and would be implemented via Terraform. A possible process outline would be as follows:
- Build the Lambda layer
- Spin up an APM-instrumented Lambda function behind an API Gateway
- Attach the extension layer to the function
- Perform 2 invocations (in order to also check [metrics generation](https://github.com/elastic/apm-aws-lambda/pull/202))
- Check a dedicated ES instance for the presence of target documents

An implementation of SAM CLI-based E2E testing already [exists](https://github.com/elastic/apm-aws-lambda/tree/main/apm-lambda-extension/e2e-testing), but since the SAM CLI does not support the Lambda Logs API used for Metrics, its relevance will decrease by the time we release `v1.1`.

**Comment by axw** [comment]
We might want to take some inspiration from https://github.com/cyrille-leclerc/my-serverless-shopping-cart/tree/main/checkout-function/deploy, which uses https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest

**Comment by simitt** [comment]
@cachedout would someone from your team be able to help out with the CI setup for the newly added smoke tests once https://github.com/elastic/apm-aws-lambda/pull/296 is finalized)?

**Comment by axw** [comment]
Reopening this - we can close it once the CI integration has been done.

**Comment by cachedout** [comment]
> @cachedout would someone from your team be able to help out with the CI setup for the newly added smoke tests once https://github.com/elastic/apm-aws-lambda/pull/296 is finalized)?

@simitt Apologies, this one slipped through my filters. It looks like this has been done by @kruskall in https://github.com/elastic/apm-aws-lambda/pull/310 and that it's currently under review. Is there anything needed beyond that?

**Comment by simitt** [comment]
Nothing more to do here.
