### ISSUE TITLE
Add release notes 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-aws-lambda#242]
Given that the lambda extension has been released as GA we need to add release notes to the public docs. 

@bmorelli25 do you have any suggestions on where to best add them to also be searchable in the docs?

**Comment by bmorelli25** [comment]
I see two options. Regardless of which option we choose, all of the dependencies for including docs from this repository already exist, so the source files for release notes can live in this repo for ease of updating at release time.

1. Outside of the agent documentation, the extension is documented in the [Monitoring AWS Lambda Functions](https://www.elastic.co/guide/en/apm/guide/current/monitoring-aws-lambda.html) bucket in the APM Guide. We could add a new subpage to this bucket with release notes. Something like this:

<img width="373" alt="Screen Shot 2022-07-18 at 11 27 40 AM" src="https://user-images.githubusercontent.com/5618806/179578186-22028588-9be0-4584-9629-b0ace56c6b6d.png">

2. Alternatively, we could add the release notes to the APM Guide release notes. The downside of this approach is that the extension is versioned separately from the stack, so we'd need a different bucket for the notes. Something like this:

<img width="366" alt="Screen Shot 2022-07-18 at 11 27 08 AM" src="https://user-images.githubusercontent.com/5618806/179578106-6e92c43c-6341-478b-94a6-ea6c676b7d2e.png">

I think it makes more sense to group all of the release notes together, as shown in option two. Thoughts?
