### ISSUE TITLE
Ensure lambda extension in Docker is 1.1.0, version in :latest image is older

### ISSUE THREAD

**Issue by richcto** [elastic/apm-aws-lambda#243]
I followed instructions to install lambda extension in Docker based lambda:

FROM docker.elastic.co/observability/apm-lambda-extension-x86_64:latest AS lambda-extension
FROM public.ecr.aws/lambda/python:3.8
COPY --from=lambda-extension /opt/elastic-apm-extension /opt/extensions/elastic-apm-extension

I tried using secret APM token from secrets manager, didn't work, error was: 

ELASTIC_APM_SECRET_TOKEN or ELASTIC_APM_API_KEY not specified

I closed this repo, recompiled, added new binary to my lambda and it started working. I suspect Docker image:latest in not 1.1.0

**Comment by simitt** [comment]
@kruskall can you take a look at this please.

**Comment by kruskall** [comment]
Thank you for the report! 😄 

version `1.1.0 has been released and I've verified `latest` is pointing to the `1.1.0` tag. I think this can be closed.
