### ISSUE TITLE
Integrate Release Notes into Elastic docs 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-aws-lambda#268]
https://github.com/elastic/apm-aws-lambda/pull/264 introduced a changelog file. The changelog should be integrated with the Elastic documentation. 

@bmorelli25 could you take a look at this please?

**Comment by bmorelli25** [comment]
I'm just realizing we're going to run into an annoying problem with these release notes.

The APM Guide is stack-versioned. For release notes from this repository to be pulled into the APM Guide, they have to live in stack-versioned branches. As-is, we'd only be able to publish this extension's release notes in the `main` branch. We'll need to backport release notes in this repository for them to show up in, for example, our `8.4` documentation.

How do you feel about this, @kruskall?

**Comment by bmorelli25** [comment]
@kruskall brought this up with Andrew, and it sounds like (at least for now) it makes more sense to just link to the release notes in this repository. I'm going to undo the work that I've done in the above PRs and add a link to the APM Guide.

@simitt I'll add a note to our sync to discuss how we want this to look in the long term. The documentation difficulties that we have in this repo are not unique—they also apply to the `apm-mutating-webhook` repo and any other new ones that pop up.
