### ISSUE TITLE
Make buffer size for agent data configurable 

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-aws-lambda#28]
Right now the size of the buffered channel for agent data is 100. We should make it configurable with some factor. n * 5, for example.
Ref: https://github.com/elastic/apm-aws-lambda/blob/main/apm-lambda-extension/main.go#L50

- [ ] test what happens if buffer is full

**Comment by simitt** [comment]
Do we have a better understanding already about what happens when the buffer is full?
