### ISSUE TITLE
Create dedicated book and make docs Elastic Stack version independent

### ISSUE THREAD

**Issue by simitt** [elastic/apm-aws-lambda#302]
Similar to how docs work for apm agents, let's introduce a separate lambda extension docs books. 

This is important to 
* better document features introduced in specific versions
* remove the stack version branches from the repository and the requirement to backport docs changes
* have better support for extension version aligned release notes
* have better support for extension | apm-server compatibility matrix

**Comment by bmorelli25** [comment]
This is now complete.
