### ISSUE TITLE
Investigate Wrapper Scripts for Automatic ENV Setting

### ISSUE THREAD

**Issue by astorm** [elastic/apm-aws-lambda#31]
AWS Lambda allows us to create wrapper scripts for starting the execution environment.  These are sometimes called "internal extensions".  

https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html

Wrapper scripts can be used by setting the `AWS_LAMBDA_EXEC_WRAPPER` variable.  When set, Lambda will run the program in this script instead of it's usual command for starting an environment. 

We should investigate whether we can use these wrapper scripts to simplify the configuration experience for end-users.  Specifically, could we

1. Allow users to continue to set `ELASTIC_APM_SERVER_URL` as the real APM Server URL
2. Use the extension script to _change_ `ELASTIC_APM_SERVER_URL` to point to the extension's URL and then _set_ the env variable [that the extension uses](https://github.com/elastic/apm-aws-lambda/issues/17).

Other questions to answer

1. How would the `AWS_LAMBDA_EXEC_WRAPPER` env variable be set?
2. How would this wrapper be packaged with the layer?
3. Could we reuse the same wrapper script for all languages? (would this be limiting us if we wanted to do language specific things in a wrapper script for the future)

**Comment by AlexanderWert** [comment]
> Could we reuse the same wrapper script for all languages?

The Java agent will need to have it's own wrapper script to attach the agent to the JVM.

**Comment by trentm** [comment]
Longer term, I'd lean to the Node.js agent have its own as well to set `NODE_OPTIONS`.

**Comment by simitt** [comment]
Refering to @AlexanderWert 's comment, can this issue be closed?
