### ISSUE TITLE
Document Tech Preview feature to collect Lambda extension logs

### ISSUE THREAD

**Issue by simitt** [elastic/apm-aws-lambda#323]
With https://github.com/elastic/apm-aws-lambda/issues/256 the lambda extension by default now has the Tech Preview feature enabled to collect logs from the lambda extension. The logs then show up in the Kibana APM UI. 

The functionality is opt-out, users can disable it by setting `ELASTIC_APM_LAMBDA_CAPTURE_LOGS=false`. 

When enabled, logs are collected and sent to the APM Server's new logs Intake API (also in Tech Preview) and indexed into Elasticsearch. 

<img width="1908" alt="Screenshot 2022-09-30 at 13 24 32" src="https://user-images.githubusercontent.com/5555349/193260370-ea4a8deb-5926-47e9-8b2a-7c91ca2f1520.png">

**Comment by lucabelluccini** [comment]
As this might create noisy logs if used against APM Server / Integration < 8.5, we should proceed documenting it if possible or switching to opt-in
