### ISSUE TITLE
Detect and report architecture (`x86_64` vs. `arm`)

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-aws-lambda#330]
**Is your feature request related to a problem? Please describe.**
The architecture of the lambda function impacts the associated costs. Collecting this information a meta field would help to do cost estimation.

**Describe the solution you'd like**

- [ ] Detect the architecture the extension is running on (`x86_64` vs. `arm`)
- [ ] Report the detected value as `host.architecture` ([ECS field](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-architecture))
- [ ] Add this field as a dimension to lambda metrics and/or transactions as part of #315

**Comment by axw** [comment]
Isn't this already reported by agents as `system.architecture` in metadata?

**Comment by AlexanderWert** [comment]
> Isn't this already reported by agents as system.architecture in metadata?

Not that I'm aware of. At least I don't see this info being available on the transaction documents.

**Comment by simitt** [comment]
@AlexanderWert if agents send `system.architecture`, it is set as `host.architecture` in the ES documents. I found a bunch of documents that contained the field in the edge example cluster.

**Comment by AlexanderWert** [comment]
Closing, as this info is already collected by agents
