### ISSUE TITLE
document agent-server communication options are not applicable to AWS lambda extension

### ISSUE THREAD

**Issue by gbanasiak** [elastic/apm-aws-lambda#349]
Due to [architecture](https://www.elastic.co/guide/en/apm/lambda/current/aws-lambda-arch.html) for AWS Lambda agent options related to agent-server communication such as [verify_server_cert](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-verify-server-cert) do not apply because agent communicates with the extension, not the APM server. This is not properly documented today. The [Configuration options](https://www.elastic.co/guide/en/apm/lambda/current/aws-lambda-config-options.html) page redirects to generic APM agent options with no caveats or restrictions.

Related: https://github.com/elastic/apm-aws-lambda/issues/186

**Comment by simitt** [comment]
@bmorelli25 could you take a look at how to reflect this in the docs?
