### ISSUE TITLE
Disable APM Agent log reporting to elasticsearch

### ISSUE THREAD

**Issue by lageorgem** [elastic/apm-aws-lambda#351]
**Is your feature request related to a problem? Please describe.**
Previously, the APM agent in the lambda layer would not send any logs to the lambda function as far as I know, or at least the logs were not correlated to a transaction.
While this feature can be useful, I prefer to keep my APM transactions unpolluted by APM agent logs in testing environments, where the agent has debug level logging.

**Describe the solution you'd like**
I would like a way to stop the agent from sending the logs to the APM server, while keeping output to regular console.log.

**Describe alternatives you've considered**
I have not found any alternatives at this time.

**Additional context**
For my use case, I keep the APM agent log level on debug, but I would much rather have these logs in cloudwatch only, and not send them to the elasticsearch server at all, as to not pollute the trace logs with useless APM debug logs.

**Comment by trentm** [comment]
@lageorgem Which APM agent language? (I know that you use the Node.js APM agent, at least.)  Can you show some example log records (e.g. the "message" field) so we could look at some concrete cases?

(I may be misremembering or unaware of some AWS Lambda *extension* feature here.)

**Comment by lageorgem** [comment]
Hello,

Sorry for forgetting about this thread. I was just looking over this issue again, and it seems that Kibana displays logs from both `logstash-*` and `.ds-logs-apm.app-default*`. It also appears that the raw winston logger event is included in the `.ds-logs.apm` index. Looks like this only happens on testing environments, even though we have `ELASTIC_APM_LOG_LEVEL` set to `error`. Do you know anything about this behaviour?

**Comment by trentm** [comment]
> and it seems that Kibana displays logs from both `logstash-*` and `.ds-logs-apm.app-default*`.

Can you describe your setup a little bit? IIUC, you have a Lambda using the Node.js APM agent. Do you also have some other Elastic component fetching data from your Lambda functions, e.g. the [AWS Lambda Elastic integration](https://docs.elastic.co/en/integrations/aws/lambda) or the [Elastic Serverless Forwarder](https://www.elastic.co/guide/en/observability/current/aws-elastic-serverless-forwarder.html)?

The Node.js APM agent may emit logs to stdout, but it doesn't currently support forwarding logs to Elastic.


> even though we have `ELASTIC_APM_LOG_LEVEL` set to `error`.

Can you show some example log records that are being ingested? That could help me track down where they are coming from.

**Comment by lageorgem** [comment]
Hey @trentm 

From logstash-* I have a log like this

message field:
```
[EventMetadataService] Saved Event Metadata
```

while from ds-logs i get something like this:

```
{"@timestamp":"2023-05-04T17:43:24.835Z","log.level":"debug","message":"[EventMetadataService] Saved Event Metadata"ecs":{"version":"1.6.0"},"event":{"dataset":"TM.log"},"trace":{"id":"7ae1658211e74ff48e3854f48c6695ae"},"transaction":{"id":"578b765304c5a32e"},"span":{"id":"664447c5dcfb6a63"},"service":{"name":"TM"}}
```

which appears to be the full log. I do not have any AWS Lambda integration enabled, and I only get logs in with [this](https://www.npmjs.com/package/winston-elasticsearch) library

**Comment by trentm** [comment]
@lageorgem I don't think this is the APM agent adding those logs. From what you say, it is the https://www.npmjs.com/package/winston-elasticsearch package that is doing so.  

Are you saying that you would like to *not* have the `"trace":{"id":"7ae1658211e74ff48e3854f48c6695ae"},"transaction":{"id":"578b765304c5a32e"},"span":{"id":"664447c5dcfb6a63"}` fields in the log record? If so, my guess is that those are being added by `winston-elasticsearch` using the `apm` option it has.

I may be confused and/or misunderstanding what you are asking, though.

**Comment by lageorgem** [comment]
Hello. No, the library is configured to send those logs to the logstash-* index, so those are the right logs. I am unsure where the .ds-logs entries are coming from. I assumed APM was creating them somehow.

**Comment by trentm** [comment]
@lageorgem Today I learned about https://www.elastic.co/guide/en/apm/lambda/current/aws-lambda-config-options.html#_elastic_apm_lambda_capture_logs
This seems likely what you are seeing. Try setting `ELASTIC_APM_LAMBDA_CAPTURE_LOGS=false` in your Lambda function config env vars.

**Comment by trentm** [comment]
Note that this is what powers the experimental "Logs" tab in the APM app for a Lambda service. E.g.:

![Screenshot 2023-05-09 at 5 03 56 PM](https://github.com/elastic/apm-aws-lambda/assets/46866/c10c1ef7-6038-49a1-afa7-87b1f66ea8dc)
