### ISSUE TITLE
Building the Go Extension on ARM

### ISSUE THREAD

**Issue by astorm** [elastic/apm-aws-lambda#37]
AWS just announced Lambda function can now choose between x86 and arm processors (with arm offering less expensive pricing)

https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

We'll need to 

- [x] add ARM options for building/compiling the extension
- [x] can cli installer detect if a function is arm or x86 to aid this?

**Comment by trentm** [comment]
Can this be closed? #drive-by
