### ISSUE TITLE
Package and distribute the extension and lambda layers as ARNs

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-aws-lambda#50]

**Comment by astorm** [comment]
Just capturing an excellent piece of information that @trentm brought to the last planning meeting. 

_If_ we want to package up the Node.js as a layer we should be able to do this without building a different layer for each version of node.  I've confirmed that an `npm install` with Node 8.17.0 and an `npm install` with node 14.16.1 produce near identical `node_modules` folders, with the only different being information in the `_where` field for the downloaded package.json files, which will have no effect on the functionality of the agent

ex.
```
diff -r 14.16.1/node_modules/@babel/code-frame/package.json 8.17.0/node_modules/@babel/code-frame/package.json
25c25
<   "_where": "/path/to/14.16.1/node_modules/parse-json",
---
>   "_where": "/path/to/8.17.0/node_modules/parse-json",
```

**Comment by AlexanderWert** [comment]
it's done
