### ISSUE TITLE
Allow Log Level Configuration for Extension

### ISSUE THREAD

**Issue by astorm** [elastic/apm-aws-lambda#60]
Right now the extension logs using Go's built-in logger, and does not have any mechanism for logging at particular levels, or turning logging on/off.  We should allow logging to happen at [the standard levels](https://github.com/elastic/apm/blob/master/specs/agents/logging.md)

**Comment by jlvoiseux** [comment]
Added a first implementation of structured logging in [dd08884](https://github.com/elastic/apm-aws-lambda/pull/136/commits/dd088846b41acba12dd505f5d17cad1c1ce4c8ce).
