### ISSUE TITLE
Reduce logging

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-aws-lambda#80]
We log a lot in the extension and it can hinder performance. We should revisit our logging strategy and optimize.

**Comment by trentm** [comment]
side snipe: Using one of the Go ecs-logging libs would be swell. :)

**Comment by jlvoiseux** [comment]
Added a first implementation of structured logging in [dd08884](https://github.com/elastic/apm-aws-lambda/pull/136/commits/dd088846b41acba12dd505f5d17cad1c1ce4c8ce). The used logger is Logrus, with our official ECS formatter. The `ELASTIC_APM_LOG_LEVEL` option is also supported.

The extension refactor following the Server team's comments is a prerequisite, but I will submit the changes for review after that.
