### ISSUE TITLE
Error: "exec format error" when using Lambda Extension 

### ISSUE THREAD

**Issue by astorm** [elastic/apm-aws-lambda#92]
We've received a few reports of folks getting the following error(s) when using the lambda extension.

```
Response
{
  "errorMessage": "RequestId: a160dc83-9aa0-4d31-93e0-62c4b77c3d79 Error: fork/exec /opt/extensions/apm-lambda-extension: exec format error",
  "errorType": "Extension.LaunchError"
}
Function Logs
START RequestId: a160dc83-9aa0-4d31-93e0-62c4b77c3d79 Version: $LATEST
EXTENSION	Name: apm-lambda-extension	State: LaunchError	Events: []	Error Type: UnknownError
END RequestId: a160dc83-9aa0-4d31-93e0-62c4b77c3d79
REPORT RequestId: a160dc83-9aa0-4d31-93e0-62c4b77c3d79	Duration: 22.66 ms	Billed Duration: 23 ms	Memory Size: 128 MB	Max Memory Used: 3 MB	
RequestId: a160dc83-9aa0-4d31-93e0-62c4b77c3d79 Error: fork/exec /opt/extensions/apm-lambda-extension: exec format error
Extension.LaunchError
```

**Comment by trentm** [comment]
At a guess: could they be attempting to use an arm64 build of the extension with an amd64 lambda runner, or vice versa?

**Comment by akhileshpok** [comment]
Yeah, I think that was probably the case for me!

I changed the extension, but now see a different error.

Akhilesh

**Comment by astorm** [comment]
Glad that fixed it @akhileshpok  -- for the record/searchers of the future -- our releases include both an AMD and ARM version of the Lambda extension. ex.

    v0-0-2-linux-amd64.zip 
    v0-0-2-linux-arm64.zip 

If you're installing the extension manually via these zips, you'll need to pick that one that matches your function's architecture.
